platform :ios,'8.0'

target 'Family' do
    pod 'ReactiveCocoa'
    pod 'CYLTabBarController'
    pod 'SDWebImage'
    pod 'SVPullToRefresh'
    pod 'SVProgressHUD'
    pod 'Weixin'
    pod 'JSONModel'
    pod 'SetupController'
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'ProgressHUD'
    pod 'KRVideoPlayer'
    pod 'YYText'
    pod 'WEPopover'
    pod 'UMengUShare/Social/QQ'
    pod 'Weixin'
    pod 'CCActivityHUD'
    use_frameworks!
end



post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "2.3"
        end
    end 
end
